import {
  AppWindow,
  ArrowRight,
  BadgeCheck,
  BadgeEuro,
  BookOpen,
  Box,
  CalendarClock,
  CheckCircle2,
  Cpu,
  CreditCard,
  Download,
  Eye,
  FileCheck,
  FileCode,
  FileX,
  FileX2,
  Film,
  Flag,
  Gauge,
  Gem,
  Gift,
  Globe,
  Headphones,
  Lightbulb,
  List,
  ListChecks,
  Lock,
  MessageCircle,
  Monitor,
  MonitorSmartphone,
  Navigation,
  PlayCircle,
  RefreshCw,
  RotateCcw,
  Scale,
  Server,
  Settings,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Tv,
  Wallet,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";
import type { ComponentType } from "react";

export type IconProps = {
  size?: number;
  className?: string;
  "aria-hidden"?: boolean | "true" | "false";
};

/**
 * Curated lucide-react icon map. Section data references icons by name; this
 * keeps the import list explicit (tree-shakeable) and crash-safe — an unknown
 * name falls back to a check icon instead of throwing.
 */
const ICONS: Record<string, ComponentType<IconProps>> = {
  AppWindow,
  ArrowRight,
  BadgeCheck,
  BadgeEuro,
  BookOpen,
  Box,
  CalendarClock,
  CheckCircle2,
  Cpu,
  CreditCard,
  Download,
  Eye,
  FileCheck,
  FileCode,
  FileX,
  FileX2,
  Film,
  Flag,
  Gauge,
  Gem,
  Gift,
  Globe,
  Headphones,
  Lightbulb,
  List,
  ListChecks,
  Lock,
  MessageCircle,
  Monitor,
  MonitorSmartphone,
  Navigation,
  PlayCircle,
  RefreshCw,
  RotateCcw,
  Scale,
  Server,
  Settings,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Tv,
  Wallet,
  Wifi,
  Wrench,
  Zap,
};

export const getIcon = (name?: string): ComponentType<IconProps> =>
  (name ? ICONS[name] : undefined) ?? CheckCircle2;
